volumes:
    langgraph-data:
        driver: local
services:
    langgraph-redis:
        image: redis:6
        healthcheck:
            test: redis-cli ping
            interval: 5s
            timeout: 1s
            retries: 5
    langgraph-postgres:
        image: postgres:16
        ports:
            - "5433:5432"
        environment:
            POSTGRES_DB: postgres
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        volumes:
            - langgraph-data:/var/lib/postgresql/data
        healthcheck:
            test: pg_isready -U postgres
            start_period: 10s
            timeout: 1s
            retries: 5
            interval: 60s
            #start_interval: 1s
    langgraph-api:
        ports:
            - "8123:8000"
        depends_on:
            langgraph-redis:
                condition: service_healthy
            langgraph-postgres:
                condition: service_healthy
        environment:
            REDIS_URI: redis://langgraph-redis:6379
            POSTGRES_URI: postgres://postgres:postgres@langgraph-postgres:5432/postgres?sslmode=disable
            LANGSMITH_API_KEY: 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
        healthcheck:
            test: python /api/healthcheck.py
            interval: 60s
            #start_interval: 1s
            start_period: 10s
        env_file: .env
        build:
            context: .
            dockerfile: Dockerfile
    neo4j:
        image: neo4j
        environment:
            NEO4J_AUTH: neo4j/abcd1234
        ports:
            - "7474:7474"
            - "7687:7687"
